//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfConsole.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfConsole.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Name.
        /// </summary>
        public static string AccesKeyName {
            get {
                return ResourceManager.GetString("AccesKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files.
        /// </summary>
        public static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        public static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Library Card.
        /// </summary>
        public static string AddLibraryCard {
            get {
                return ResourceManager.GetString("AddLibraryCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license is expired, administrators can only search and view items..
        /// </summary>
        public static string AdminExpiredLicense {
            get {
                return ResourceManager.GetString("AdminExpiredLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Account.
        /// </summary>
        public static string AdministrativeAccount {
            get {
                return ResourceManager.GetString("AdministrativeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ark Name.
        /// </summary>
        public static string ArkName {
            get {
                return ResourceManager.GetString("ArkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade License File.
        /// </summary>
        public static string AttachLicenseFile {
            get {
                return ResourceManager.GetString("AttachLicenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Load.
        /// </summary>
        public static string AutoLoad {
            get {
                return ResourceManager.GetString("AutoLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Auto Loaded.
        /// </summary>
        public static string AutoLoadLastRun {
            get {
                return ResourceManager.GetString("AutoLoadLastRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string BaseGroupName {
            get {
                return ResourceManager.GetString("BaseGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Search Name.
        /// </summary>
        public static string BinderName {
            get {
                return ResourceManager.GetString("BinderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse HardDisk.
        /// </summary>
        public static string BrowseHardDisk {
            get {
                return ResourceManager.GetString("BrowseHardDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Checked Out.
        /// </summary>
        public static string CheckedOut {
            get {
                return ResourceManager.GetString("CheckedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Checked Out Views (left menu).
        /// </summary>
        public static string CheckedOutViews {
            get {
                return ResourceManager.GetString("CheckedOutViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Occurred while canceling the check in.
        /// </summary>
        public static string CheckInCancelError {
            get {
                return ResourceManager.GetString("CheckInCancelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR Occurred during check in.
        /// </summary>
        public static string CheckInError {
            get {
                return ResourceManager.GetString("CheckInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Configuration.
        /// </summary>
        public static string ConfigureAutoload {
            get {
                return ResourceManager.GetString("ConfigureAutoload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ConnectionAddress {
            get {
                return ResourceManager.GetString("ConnectionAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Entries (left menu).
        /// </summary>
        public static string ConnectionEntries {
            get {
                return ResourceManager.GetString("ConnectionEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Name.
        /// </summary>
        public static string ConnectionName {
            get {
                return ResourceManager.GetString("ConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string ConnectionPort {
            get {
                return ResourceManager.GetString("ConnectionPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Setup.
        /// </summary>
        public static string ConnectionTitle {
            get {
                return ResourceManager.GetString("ConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Ark.
        /// </summary>
        public static string CreateArk {
            get {
                return ResourceManager.GetString("CreateArk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string Criteria {
            get {
                return ResourceManager.GetString("Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning Date.
        /// </summary>
        public static string DateBegin {
            get {
                return ResourceManager.GetString("DateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Date.
        /// </summary>
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want to Delete.
        /// </summary>
        public static string DeleteMessageBox {
            get {
                return ResourceManager.GetString("DeleteMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently running a full function demo license. It is Valid for {0} more days..
        /// </summary>
        public static string DemoLicense {
            get {
                return ResourceManager.GetString("DemoLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories To Scan.
        /// </summary>
        public static string DirectoriesToScan {
            get {
                return ResourceManager.GetString("DirectoriesToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DocumentDate {
            get {
                return ResourceManager.GetString("DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name.
        /// </summary>
        public static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string DocumentPath {
            get {
                return ResourceManager.GetString("DocumentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Files Here.
        /// </summary>
        public static string DropFilesHere {
            get {
                return ResourceManager.GetString("DropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This is your library card.&lt;/p&gt;&lt;p&gt;Please add the attached file to your applications connection list.&lt;/p&gt;&lt;p&gt;You can also cut and paste the code below into the connection list.&lt;/p&gt;&lt;p&gt;{0}&lt;/p&gt;.
        /// </summary>
        public static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Card.
        /// </summary>
        public static string EmailCardSubject {
            get {
                return ResourceManager.GetString("EmailCardSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email Addresses.
        /// </summary>
        public static string EmailEnterText {
            get {
                return ResourceManager.GetString("EmailEnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lewisbass@gmail.com.
        /// </summary>
        public static string EmailFromAddress {
            get {
                return ResourceManager.GetString("EmailFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lewis Bass.
        /// </summary>
        public static string EmailFromName {
            get {
                return ResourceManager.GetString("EmailFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        public static string EmailHost {
            get {
                return ResourceManager.GetString("EmailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lewisbass@gmail.com.
        /// </summary>
        public static string EmailHostLogin {
            get {
                return ResourceManager.GetString("EmailHostLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gobez08172010.
        /// </summary>
        public static string EmailHostPassword {
            get {
                return ResourceManager.GetString("EmailHostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 587.
        /// </summary>
        public static string EmailHostPort {
            get {
                return ResourceManager.GetString("EmailHostPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter PIN for {0}.
        /// </summary>
        public static string EnterPIN {
            get {
                return ResourceManager.GetString("EnterPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the Library Card - it can not be used..
        /// </summary>
        public static string ErrorBadLibraryCard {
            get {
                return ResourceManager.GetString("ErrorBadLibraryCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Current Password is incorrect.
        /// </summary>
        public static string ErrorBadPassword {
            get {
                return ResourceManager.GetString("ErrorBadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not continue - no tag name was selected.
        /// </summary>
        public static string ErrorEmptyTag {
            get {
                return ResourceManager.GetString("ErrorEmptyTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Library Card was not found.
        /// </summary>
        public static string ErrorMissingLibraryCard {
            get {
                return ResourceManager.GetString("ErrorMissingLibraryCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Passwords must match.
        /// </summary>
        public static string ErrorNewPasswordMatch {
            get {
                return ResourceManager.GetString("ErrorNewPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New Password is Required.
        /// </summary>
        public static string ErrorNewPasswordMissing {
            get {
                return ResourceManager.GetString("ErrorNewPasswordMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Current Password is Required.
        /// </summary>
        public static string ErrorOldPasswordMissing {
            get {
                return ResourceManager.GetString("ErrorOldPasswordMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire.
        /// </summary>
        public static string Expire {
            get {
                return ResourceManager.GetString("Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license has expired. Please contact support or purchace the full license..
        /// </summary>
        public static string ExpiredLicense {
            get {
                return ResourceManager.GetString("ExpiredLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Matching File.
        /// </summary>
        public static string FileBrowserTypeTitle {
            get {
                return ResourceManager.GetString("FileBrowserTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Extension.
        /// </summary>
        public static string FileExtension {
            get {
                return ResourceManager.GetString("FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileNameColumn {
            get {
                return ResourceManager.GetString("FileNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Transfer Completed.
        /// </summary>
        public static string FileTransferCompleted {
            get {
                return ResourceManager.GetString("FileTransferCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum File Views (left menu).
        /// </summary>
        public static string FileViews {
            get {
                return ResourceManager.GetString("FileViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string FilterTree {
            get {
                return ResourceManager.GetString("FilterTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Information.
        /// </summary>
        public static string HostInformation {
            get {
                return ResourceManager.GetString("HostInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Rights.
        /// </summary>
        public static string KeyAdmin {
            get {
                return ResourceManager.GetString("KeyAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In/Out.
        /// </summary>
        public static string KeyCheckInOut {
            get {
                return ResourceManager.GetString("KeyCheckInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be greater than today.
        /// </summary>
        public static string KeyDateAfterNow {
            get {
                return ResourceManager.GetString("KeyDateAfterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string KeyDevices {
            get {
                return ResourceManager.GetString("KeyDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string KeyDownload {
            get {
                return ResourceManager.GetString("KeyDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string KeyEmail {
            get {
                return ResourceManager.GetString("KeyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        public static string KeyExpiration {
            get {
                return ResourceManager.GetString("KeyExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date is Required.
        /// </summary>
        public static string KeyExpiredRequired {
            get {
                return ResourceManager.GetString("KeyExpiredRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string KeyName {
            get {
                return ResourceManager.GetString("KeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is Required.
        /// </summary>
        public static string KeyNameRequired {
            get {
                return ResourceManager.GetString("KeyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        public static string KeyPin {
            get {
                return ResourceManager.GetString("KeyPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN must be a number.
        /// </summary>
        public static string KeyPinNumeric {
            get {
                return ResourceManager.GetString("KeyPinNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN is Required.
        /// </summary>
        public static string KeyPinRequired {
            get {
                return ResourceManager.GetString("KeyPinRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        public static string Keys {
            get {
                return ResourceManager.GetString("Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit New Files.
        /// </summary>
        public static string KeySubmit {
            get {
                return ResourceManager.GetString("KeySubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        public static string KeyTitle {
            get {
                return ResourceManager.GetString("KeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Files.
        /// </summary>
        public static string KeyView {
            get {
                return ResourceManager.GetString("KeyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string LanguageSpanish {
            get {
                return ResourceManager.GetString("LanguageSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last CheckOuts.
        /// </summary>
        public static string LastCheckOuts {
            get {
                return ResourceManager.GetString("LastCheckOuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Scan.
        /// </summary>
        public static string LastFileUploadDate {
            get {
                return ResourceManager.GetString("LastFileUploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Changed.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string LastUploadCount {
            get {
                return ResourceManager.GetString("LastUploadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastViewed.
        /// </summary>
        public static string LastViewed {
            get {
                return ResourceManager.GetString("LastViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Card.
        /// </summary>
        public static string LibraryCard {
            get {
                return ResourceManager.GetString("LibraryCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Library Card File.
        /// </summary>
        public static string LibraryCardFile {
            get {
                return ResourceManager.GetString("LibraryCardFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Library Card Text Message.
        /// </summary>
        public static string LibraryCardTextMessage {
            get {
                return ResourceManager.GetString("LibraryCardTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Files.
        /// </summary>
        public static string LoadFiles {
            get {
                return ResourceManager.GetString("LoadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan/Load files from directories Below.
        /// </summary>
        public static string LoadFilesFromDirectory {
            get {
                return ResourceManager.GetString("LoadFilesFromDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Admin.
        /// </summary>
        public static string LocalAdminName {
            get {
                return ResourceManager.GetString("LocalAdminName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Path.
        /// </summary>
        public static string LocalPath {
            get {
                return ResourceManager.GetString("LocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login .
        /// </summary>
        public static string LoginInformation {
            get {
                return ResourceManager.GetString("LoginInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successful.
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Address.
        /// </summary>
        public static string ManualIP {
            get {
                return ResourceManager.GetString("ManualIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Match.
        /// </summary>
        public static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show My CheckOuts.
        /// </summary>
        public static string MyCheckOuts {
            get {
                return ResourceManager.GetString("MyCheckOuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Documents].
        /// </summary>
        public static string MyDocuments {
            get {
                return ResourceManager.GetString("MyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Music].
        /// </summary>
        public static string MyMusic {
            get {
                return ResourceManager.GetString("MyMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Pictures].
        /// </summary>
        public static string MyPictures {
            get {
                return ResourceManager.GetString("MyPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File When Checked in.
        /// </summary>
        public static string MyRemoveCheckIn {
            get {
                return ResourceManager.GetString("MyRemoveCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Video].
        /// </summary>
        public static string MyVideo {
            get {
                return ResourceManager.GetString("MyVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your File Name.
        /// </summary>
        public static string OutputFileName {
            get {
                return ResourceManager.GetString("OutputFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN Is Required for the connection.
        /// </summary>
        public static string PINRequired {
            get {
                return ResourceManager.GetString("PINRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Searches.
        /// </summary>
        public static string PreviousSearches {
            get {
                return ResourceManager.GetString("PreviousSearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prior Connections.
        /// </summary>
        public static string PriorConnections {
            get {
                return ResourceManager.GetString("PriorConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RekeyPassword.
        /// </summary>
        public static string RekeyPassword {
            get {
                return ResourceManager.GetString("RekeyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Search Critera must be met.
        /// </summary>
        public static string RelationshipAndHelp {
            get {
                return ResourceManager.GetString("RelationshipAndHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Search Critera must be met.
        /// </summary>
        public static string RelationshipOrHelp {
            get {
                return ResourceManager.GetString("RelationshipOrHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is Required.
        /// </summary>
        public static string RequiredAddress {
            get {
                return ResourceManager.GetString("RequiredAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Search Criteria not entered.
        /// </summary>
        public static string RequiredCriteria {
            get {
                return ResourceManager.GetString("RequiredCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is Required.
        /// </summary>
        public static string RequiredLogin {
            get {
                return ResourceManager.GetString("RequiredLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is Required.
        /// </summary>
        public static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Required.
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port is Required.
        /// </summary>
        public static string RequiredPort {
            get {
                return ResourceManager.GetString("RequiredPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must be a number.
        /// </summary>
        public static string RequiredPortNumber {
            get {
                return ResourceManager.GetString("RequiredPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Results.
        /// </summary>
        public static string SaveAndExecute {
            get {
                return ResourceManager.GetString("SaveAndExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Network.
        /// </summary>
        public static string ScanNetwork {
            get {
                return ResourceManager.GetString("ScanNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string SearchField {
            get {
                return ResourceManager.GetString("SearchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string SearchFieldClassification {
            get {
                return ResourceManager.GetString("SearchFieldClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string SearchFieldDate {
            get {
                return ResourceManager.GetString("SearchFieldDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string SearchFieldExtension {
            get {
                return ResourceManager.GetString("SearchFieldExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string SearchFieldFileName {
            get {
                return ResourceManager.GetString("SearchFieldFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string SearchFieldLocked {
            get {
                return ResourceManager.GetString("SearchFieldLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string SearchFieldPath {
            get {
                return ResourceManager.GetString("SearchFieldPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prior Versions.
        /// </summary>
        public static string SearchFieldPriorVersions {
            get {
                return ResourceManager.GetString("SearchFieldPriorVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How.
        /// </summary>
        public static string SearchHow {
            get {
                return ResourceManager.GetString("SearchHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string SearchHowContains {
            get {
                return ResourceManager.GetString("SearchHowContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string SearchHowList {
            get {
                return ResourceManager.GetString("SearchHowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string SearchHowRange {
            get {
                return ResourceManager.GetString("SearchHowRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle Multiple Searches as.
        /// </summary>
        public static string SearchJoinText {
            get {
                return ResourceManager.GetString("SearchJoinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a Unique Name for the Search.
        /// </summary>
        public static string SearchSaveName {
            get {
                return ResourceManager.GetString("SearchSaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string SearchValues {
            get {
                return ResourceManager.GetString("SearchValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Theme.
        /// </summary>
        public static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Location.
        /// </summary>
        public static string StorageLocation {
            get {
                return ResourceManager.GetString("StorageLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string SystemDirectory {
            get {
                return ResourceManager.GetString("SystemDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string TagAdd {
            get {
                return ResourceManager.GetString("TagAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new tag name.
        /// </summary>
        public static string TagAddNew {
            get {
                return ResourceManager.GetString("TagAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists and can not be added.
        /// </summary>
        public static string TagAttemptDuplicateAdd {
            get {
                return ResourceManager.GetString("TagAttemptDuplicateAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Tags.
        /// </summary>
        public static string TagChange {
            get {
                return ResourceManager.GetString("TagChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine.
        /// </summary>
        public static string TagCombine {
            get {
                return ResourceManager.GetString("TagCombine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag {0} will be combined with the value selected below.
        /// </summary>
        public static string TagCombineString {
            get {
                return ResourceManager.GetString("TagCombineString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm the deletion of tag {0}.
        /// </summary>
        public static string TagDeleteRecord {
            get {
                return ResourceManager.GetString("TagDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tag Name.
        /// </summary>
        public static string TagEnterName {
            get {
                return ResourceManager.GetString("TagEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Tags.
        /// </summary>
        public static string TagExisting {
            get {
                return ResourceManager.GetString("TagExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string TagName {
            get {
                return ResourceManager.GetString("TagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string TagRename {
            get {
                return ResourceManager.GetString("TagRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new name for {0}.
        /// </summary>
        public static string TagRenameString {
            get {
                return ResourceManager.GetString("TagRenameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files without tags.
        /// </summary>
        public static string TagsNotFound {
            get {
                return ResourceManager.GetString("TagsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string TagUsage {
            get {
                return ResourceManager.GetString("TagUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        public static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserNameColumn {
            get {
                return ResourceManager.GetString("UserNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault.
        /// </summary>
        public static string Vault {
            get {
                return ResourceManager.GetString("Vault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
